// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcxgtvpidssphotnuged.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjeGd0dnBpZHNzcGhvdG51Z2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjgzNjgsImV4cCI6MjA2NTgwNDM2OH0.VaBuiXOv1c1pkqf7LklOSp1DisNgdDhXuHXaQameoL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);